import React from 'react';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '../ui/accordion';

export const FrequentQuestionAnswer = () => {
    const faqs = [
        {
            trigger: "Why did you make this site?",
            content: `Ever been in a job interview for your dream role, only to completely blank on all your answers? Or maybe you spent all night prepping, but they didn’t even ask anything you prepared for? Us too. It’s not fun. \n\n
        With the current job market and ongoing recession, interviews just became that much more important and stressful.
        \n\n
        Interviews by AI wants to make your next job interview stress-free by boosting your confidence, calming your nerves, and helping you land that job. Our AI tool accomplishes this by leveraging groundbreaking technologies like GPT-3.5 (ChatGPT) to deliver hyper-realistic interview questions and answers along with actionable feedback.
        \n\n
        It's the closest you'll get to the actual questions in an interview.`,
        },
        {
            trigger: "How accurate are the AI interview questions and feedback?",
            content: `The interview questions are AI-generated by our site and are based on either the job description you provide, or on general sample descriptions that we've curated. The more detailed the job description, the more accurately the AI can tailor interview questions to the specific skills, requirements, roles, and experience outlined. \n \n
            As for the feedback, it’s based on a combination of the job description, the specific interview question asked, and your recorded answer. It's important to note that, on rare occasions, the AI may 'hallucinate', but generally, it provides accurate and helpful feedback. \n\n
            We’ve invested a lot of time and research into creating effective prompts that result in great questions, feedback, and general interview tips.`,
        },
        {
            trigger: "Can I use this site to practice interviews for any job role?",
            content: `Yes, you can! Our AI generates interview questions and feedback based on the job description you provide, which makes it great for a wide range of job roles. \n \n
            It's especially valuable for those looking for interns, early-career roles, or transitioning to a new role or field, as it offers a safe environment to practice and hone their interview techniques and skills. \n \n
            That being said, you can absolutely prepare for interviews at any level.`,
        },
        {
            trigger: "How is this different than using ChatGPT?",
            content: `While ChatGPT is an incredibly versatile tool, Interviews by AI is an AI tool uniquely designed to provide a more specialized experience for interview preparation. Here’s how we stand apart:

            Expertly crafted prompts behind the scenes to generate better interview questions and answers. \n \n

            Streamlined UI and experience that more closely mimics what you’d expect in real life. \n \n

            Enhanced features such as audio input, and a dashboard to save and review interviews. \n \n`,
        },
        {
            trigger: "What languages do you support?",
            content: `Currently, our platform supports English. This means that the job description, generated questions, feedback, and sample responses are all provided in English. You can technically record your answers in almost any language and it will be translated to English. \n \n
            We understand and appreciate that there are potential users from all over the world who could benefit from our Interviews by AI. We would love to expand our language support in the future and help even more people, so hang tight!`,
        },
        {
            trigger: "Do you keep my data and audio files?",
            content: `For all users, we track events such as button clicks to help us understand how our site is used and to improve the user experience, but we do this anonymously. \n \n
            For users who choose to log in, we save your interview data automatically so you can review it from your dashboard. This includes the name and email associated with the Google account used to sign in. Please note that this is primarily done to enhance your experience and to provide personalized services. \n \n

            As for audio files and recordings, they are deleted immediately after they've been transcribed. We do not store your audio recordings once the transcription process is completed. We understand the sensitive nature of voice data and have policies in place to ensure your peace of mind.`,
        },
        {
            trigger: "Is it free to use?",
            content: `We offer free plan for our users. Our free plan gives you 5 questions of each Interview`,
        },
    ];

    return (
        <Accordion type="single" collapsible className="w-full max-w-3xl mx-auto my-12 space-y-2">
            {faqs.map((faq, index) => (
                <AccordionItem key={index} value={`item-${index}`} className="w-full border-b border-gray-300">
                    <AccordionTrigger className="p-5 bg-secondary text-xl font-semibold flex justify-between items-center w-full hover:bg-gray-100 transition duration-500 rounded-t-xl">
                        {faq.trigger}
                    </AccordionTrigger>
                    <AccordionContent className="p-4 text-base">
                        {faq.content}
                    </AccordionContent>
                </AccordionItem>
            ))}
        </Accordion>
    );
};